version: '3.8'

services:
  # Backend service
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=your-production-secret-key
      - JWT_SECRET_KEY=your-production-jwt-secret-key
      - DATABASE_URL=sqlite:///database.db
      - UPLOAD_FOLDER=uploads
    volumes:
      - ./backend/uploads:/app/uploads
      - backend_data:/app
    networks:
      - app-network

  # Frontend development service (for development only)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_BASE_URL=http://backend:5000/api
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  backend_data:

networks:
  app-network:
    driver: bridge