services:
  - type: web
    name: project-tracker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: UPLOAD_FOLDER
        value: uploads
      - key: PYTHON_VERSION
        value: 3.9.18